name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'

    - name: Install Angular CLI
      run: npm install -g @angular/cli@12.2.17

    - name: Install dependencies
      run: npm install

    - name: Build
      run: ng build --base-href=/english-assist/

    - name: Build ngh
      run: npx ngh --dir=public

    - name: Deploy
      if: success()
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      with:
        publish_dir: public
